name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    name: Upload release to PyPI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Check tag matches __version__
      run: |
        TAG=${GITHUB_REF#refs/tags/v}
        VERSION=$(python -c "import textcleaner.version as v; print(v.__version__)")
        if [ "$TAG" != "$VERSION" ]; then
          echo "❌ Tag ($TAG) doesn't match version ($VERSION)"
          exit 1
        fi

    - name: Build package
      run: python -m build

    - name: Publish package to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: twine upload dist/*
